CREATE TABLE IF NOT EXISTS notification_preference (
  user_id BIGINT NOT NULL PRIMARY KEY,
  browser_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  task_assigned_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  task_status_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  reminder_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
