export const labels = {
  appTitle: '日程提醒',
  appSubtitle: '个人日程与小团队任务协作工具。',
  phone: '手机号', password: '密码', login: '登录',
  user: '用户', logout: '退出登录',
  today: '今天', newItem: '新建', refresh: '刷新', pendingSchedules: '待办日程',
  teamTasks: '团队任务', unreadNotifications: '未读通知', upcomingWork: '近期任务', add: '添加',
  timeline: '时间轴', overdue: '逾期', monthCalendar: '本月日历', items: '项', upcomingItems: '近期事项',
  newSchedule: '新建日程', undo: '恢复', complete: '完成', title: '标题', type: '类型',
  deadlineTask: '待办任务', pointEvent: '安排事项', durationTask: '时间段任务', occurTime: '发生时间', startTime: '开始时间', endTime: '结束时间', deadlineTime: '截止时间',
  cancel: '取消', save: '保存', module: '模块', modules: '任务模块', moduleName: '模块名称', addModule: '添加模块', rename: '重命名', delete: '删除', noModules: '请先在「我的」里添加模块',
  teams: '团队', teamName: '团队名称', create: '创建', inviteCode: '邀请码',
  members: '成员', tasks: '任务', team: '团队', taskTitle: '任务标题', assigneeIds: '执行人用户 ID，逗号分隔',
  accept: '接受', reject: '拒绝', taskDetail: '任务详情',
  notifications: '通知', readAll: '全部已读', unread: '未读', timezone: '时区：',
  register: '注册', confirmPassword: '确认密码', nickname: '昵称', registerTitle: '注册账号',
  settings: '设置', profileSettings: '个人设置', oldPassword: '旧密码', newPassword: '新密码',
  profile: '个人资料', changePassword: '修改密码', timezoneSettings: '时区设置',
  joinTeam: '加入团队', createTeam: '创建团队', teamDetail: '团队详情',
  scheduleDetail: '日程详情', notificationDetail: '通知详情',
  status: '状态', description: '描述', creator: '创建者',
  reassign: '重新分配', restore: '恢复', details: '详情',
  teamTaskDetail: '团队任务详情', assignees: '执行人',
  edit: '编辑', action: '操作', role: '角色', joinedAt: '加入时间',
  current: '当前', round: '轮次',
  noData: '暂无数据',
  confirmDelete: '确认删除？',
  createAdmin: '创建管理员',
}
